domain: Cerebro.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://Cerebro.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /Cerebro.github.io/    # place folder name if the site is served in a subfolder
theme: midnight
title: KAPS 
description: Bookmark this to keep an eye on my project updates!